name: Ejecutar DatesReminder cada dos días

on:
  schedule:
    - cron: '0 0 */2 * *'  # Ejecutar a medianoche cada dos días

jobs:
  run_dates_reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Especificar la versión de Python

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar DatesReminder
        run: python DatesReminder.py